site_name: Cybersources

theme:
    name: 'material'
    font:
      text: Open Sans
      code: Cousine

    features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.integrate
    - navigation.indexes
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition

plugins:
  - search
  - roamlinks 
  - mermaid2

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 

nav:
  - Home: 
    - index.md 
  
  - Tools:
    - Tools/Education Platforms.md
    - Tools/OSINT.md 
    - Tools/Hashes and Passwords.md 
    - Tools/Domain Tools.md 
    - Tools/Misc.md 
    - Tools/Resources.md 

  - Red Team:
    - Redteam/Resources.md
    - Redteam/Reverse Shells.md 
    - Redteam/CI-CD.md
    - Redteam/SQL.md

  - Blue Team:
    - Blueteam/Crowdstrike Falcon.md

  - Windows:
    - Windows/Common Services.md 
